
title: dua3

baseurl: ""
permalink: /:title/
markdown: kramdown
theme: minima

plugins:
  - jekyll-multiple-languages-plugin

# multilanguage
languages: ["en", "en", "de", "fr"]

# nav
header_pages: 
 - index.md
 - apps/index.md
 - imprint.md
